name: taxi_rides_hourly_features_pipeline

on:
  schedule:
    - cron: '2 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_feature_pipeline.txt

      # Remove corrupted February file
      - name: Remove corrupted February file
        run: |
          if [ -f data/raw/rides_2024_02.parquet ]; then
            echo "Removing corrupted rides_2024_02.parquet..."
            rm -f data/raw/rides_2024_02.parquet
          else
            echo "rides_2024_02.parquet does not exist. Skipping removal."
          fi

      # Remove corrupted March file
      - name: Remove corrupted March file
        run: |
          if [ -f data/raw/rides_2024_03.parquet ]; then
            echo "Removing corrupted rides_2024_03.parquet..."
            rm -f data/raw/rides_2024_03.parquet
          else
            echo "rides_2024_03.parquet does not exist. Skipping removal."
          fi

      - name: List raw data folder
        run: ls -al data/raw/

      - name: Run new data fetch pipeline and load to hopsworks
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        run: python -m src.feature_pipeline
